library("devtools")
updateR()
devtools::install_github("google/CausalImpact", force = TRUE)
install.packages("devtools")
install.packages("C:/Users/HS/Downloads/Boom_0.5.zip", repos = NULL)
library(devtools)
library(CausalImpact)

webtraffic <-read.table("C:/Users/HS/Desktop/BDAP/Case Study/Case Study 10 - Campaign/Campaign.csv", quote = "\"",comment.char = "")
Traffic <- data.frame(webtraffic)
dim(Traffic)
head(Traffic)
time.points <- seq.Date(as.Date("2014-12-27"), by = 1, length.out = 50)
data <- zoo(cbind(webtraffic), time.points)
class(data)
pre.period <- as.Date(c("2014-12-27","2015-01-26"))
post.period <- as.Date(c("2015-01-27","2015-02-14"))
Res <- CausalImpact(data,pre.period,post.period)
plot(Res)
summary(Res,"report")
