///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace RanorexDemo
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the RanorexDemoRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    [RepositoryFolder("a51218a7-459b-436d-b43f-50a8126b02a4")]
    public partial class RanorexDemoRepository : RepoGenBaseFolder
    {
        static RanorexDemoRepository instance = new RanorexDemoRepository();
        RanorexDemoRepositoryFolders.MercuryAppFolder _mercury;
        RanorexDemoRepositoryFolders.MercuryFlightAppFolder _mercuryflight;

        /// <summary>
        /// Gets the singleton class instance representing the RanorexDemoRepository element repository.
        /// </summary>
        [RepositoryFolder("a51218a7-459b-436d-b43f-50a8126b02a4")]
        public static RanorexDemoRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public RanorexDemoRepository() 
            : base("RanorexDemoRepository", "/", null, 0, false, "a51218a7-459b-436d-b43f-50a8126b02a4", ".\\RepositoryImages\\RanorexDemoRepositorya51218a7.rximgres")
        {
            _mercury = new RanorexDemoRepositoryFolders.MercuryAppFolder(this);
            _mercuryflight = new RanorexDemoRepositoryFolders.MercuryFlightAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("a51218a7-459b-436d-b43f-50a8126b02a4")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Mercury folder.
        /// </summary>
        [RepositoryFolder("ffa7b769-9e24-4fcd-bcc2-c344a4a19910")]
        public virtual RanorexDemoRepositoryFolders.MercuryAppFolder Mercury
        {
            get { return _mercury; }
        }

        /// <summary>
        /// The MercuryFlight folder.
        /// </summary>
        [RepositoryFolder("f43b7194-26f3-4492-b36b-13ad496843b6")]
        public virtual RanorexDemoRepositoryFolders.MercuryFlightAppFolder MercuryFlight
        {
            get { return _mercuryflight; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
    public partial class RanorexDemoRepositoryFolders
    {
        /// <summary>
        /// The MercuryAppFolder folder.
        /// </summary>
        [RepositoryFolder("ffa7b769-9e24-4fcd-bcc2-c344a4a19910")]
        public partial class MercuryAppFolder : RepoGenBaseFolder
        {
            RanorexDemoRepositoryFolders.HomeFolder _home;

            /// <summary>
            /// Creates a new Mercury  folder.
            /// </summary>
            public MercuryAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Mercury", "/dom[@domain='demoaut.com']", parentFolder, 30000, null, false, "ffa7b769-9e24-4fcd-bcc2-c344a4a19910", "")
            {
                _home = new RanorexDemoRepositoryFolders.HomeFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("ffa7b769-9e24-4fcd-bcc2-c344a4a19910")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("ffa7b769-9e24-4fcd-bcc2-c344a4a19910")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Home folder.
            /// </summary>
            [RepositoryFolder("df092cbe-1535-4391-8d51-dff2c77ff24b")]
            public virtual RanorexDemoRepositoryFolders.HomeFolder Home
            {
                get { return _home; }
            }
        }

        /// <summary>
        /// The HomeFolder folder.
        /// </summary>
        [RepositoryFolder("df092cbe-1535-4391-8d51-dff2c77ff24b")]
        public partial class HomeFolder : RepoGenBaseFolder
        {
            RepoItemInfo _usernameInfo;
            RepoItemInfo _passwordInfo;
            RepoItemInfo _loginInfo;

            /// <summary>
            /// Creates a new Home  folder.
            /// </summary>
            public HomeFolder(RepoGenBaseFolder parentFolder) :
                    base("Home", ".//table/?/?/tr/td[2]/table/tbody/tr[4]/?/?/table/?/?/tr/td[2]/table/tbody/tr[2]/td[3]/form[@name='home']/table/tbody/tr[4]/?/?/table", parentFolder, 30000, null, false, "df092cbe-1535-4391-8d51-dff2c77ff24b", "")
            {
                _usernameInfo = new RepoItemInfo(this, "UserName", "tbody/tr[2]/td[2]/input[@name='userName']", 30000, null, "b0d22b6d-d50d-4558-bca9-0d783f3ee7ea");
                _passwordInfo = new RepoItemInfo(this, "Password", "tbody/tr[3]/td[2]/input[@name='password']", 30000, null, "b066c413-55ca-47b4-98ad-0261afe03fd3");
                _loginInfo = new RepoItemInfo(this, "Login", "tbody/tr[4]/td[2]/?/?/input[@name='login']", 30000, null, "5d75e194-b121-46b6-99aa-30ce06a90ac8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("df092cbe-1535-4391-8d51-dff2c77ff24b")]
            public virtual Ranorex.Table Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("df092cbe-1535-4391-8d51-dff2c77ff24b")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The UserName item.
            /// </summary>
            [RepositoryItem("b0d22b6d-d50d-4558-bca9-0d783f3ee7ea")]
            public virtual Ranorex.InputTag UserName
            {
                get
                {
                    return _usernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The UserName item info.
            /// </summary>
            [RepositoryItemInfo("b0d22b6d-d50d-4558-bca9-0d783f3ee7ea")]
            public virtual RepoItemInfo UserNameInfo
            {
                get
                {
                    return _usernameInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("b066c413-55ca-47b4-98ad-0261afe03fd3")]
            public virtual Ranorex.InputTag Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("b066c413-55ca-47b4-98ad-0261afe03fd3")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The Login item.
            /// </summary>
            [RepositoryItem("5d75e194-b121-46b6-99aa-30ce06a90ac8")]
            public virtual Ranorex.InputTag Login
            {
                get
                {
                    return _loginInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Login item info.
            /// </summary>
            [RepositoryItemInfo("5d75e194-b121-46b6-99aa-30ce06a90ac8")]
            public virtual RepoItemInfo LoginInfo
            {
                get
                {
                    return _loginInfo;
                }
            }
        }

        /// <summary>
        /// The MercuryFlightAppFolder folder.
        /// </summary>
        [RepositoryFolder("f43b7194-26f3-4492-b36b-13ad496843b6")]
        public partial class MercuryFlightAppFolder : RepoGenBaseFolder
        {
            RanorexDemoRepositoryFolders.BookAFlightFolder _bookaflight;
            RanorexDemoRepositoryFolders.FlightConfirmationFolder _flightconfirmation;
            RepoItemInfo _outflightInfo;
            RepoItemInfo _itineraryconfimrationInfo;

            /// <summary>
            /// Creates a new MercuryFlight  folder.
            /// </summary>
            public MercuryFlightAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MercuryFlight", "/dom[@domain='newtours.demoaut.com']", parentFolder, 30000, null, false, "f43b7194-26f3-4492-b36b-13ad496843b6", "")
            {
                _bookaflight = new RanorexDemoRepositoryFolders.BookAFlightFolder(this);
                _flightconfirmation = new RanorexDemoRepositoryFolders.FlightConfirmationFolder(this);
                _outflightInfo = new RepoItemInfo(this, "OutFlight", ".//table/?/?/tr/td[2]/table/tbody/tr[4]/?/?/table/?/?/tr/td[2]/table/tbody/tr[5]/?/?/form[@name='results']/table[1]/tbody/tr[5]/td[1]/input[@name='outFlight']", 30000, null, "23434dde-db40-40a9-b543-b618fc5323c6");
                _itineraryconfimrationInfo = new RepoItemInfo(this, "ItineraryConfimration", ".//table/?/?/tr/td[2]/table/tbody/tr[4]/?/?/table/tbody/tr[1]/td[2]/table/tbody/tr[3]//font[@innertext~'^\\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ Please']/b/font[@innertext~'^Your\\ \\ \\ \\ \\ \\ \\ \\ \\ itinerary\\ h']", 30000, null, "5b3b4ff2-a182-414e-9e30-93eb297ac5fe");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f43b7194-26f3-4492-b36b-13ad496843b6")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f43b7194-26f3-4492-b36b-13ad496843b6")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The OutFlight item.
            /// </summary>
            [RepositoryItem("23434dde-db40-40a9-b543-b618fc5323c6")]
            public virtual Ranorex.InputTag OutFlight
            {
                get
                {
                    return _outflightInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The OutFlight item info.
            /// </summary>
            [RepositoryItemInfo("23434dde-db40-40a9-b543-b618fc5323c6")]
            public virtual RepoItemInfo OutFlightInfo
            {
                get
                {
                    return _outflightInfo;
                }
            }

            /// <summary>
            /// The ItineraryConfimration item.
            /// </summary>
            [RepositoryItem("5b3b4ff2-a182-414e-9e30-93eb297ac5fe")]
            public virtual Ranorex.FontTag ItineraryConfimration
            {
                get
                {
                    return _itineraryconfimrationInfo.CreateAdapter<Ranorex.FontTag>(true);
                }
            }

            /// <summary>
            /// The ItineraryConfimration item info.
            /// </summary>
            [RepositoryItemInfo("5b3b4ff2-a182-414e-9e30-93eb297ac5fe")]
            public virtual RepoItemInfo ItineraryConfimrationInfo
            {
                get
                {
                    return _itineraryconfimrationInfo;
                }
            }

            /// <summary>
            /// The BookAFlight folder.
            /// </summary>
            [RepositoryFolder("08c177fb-6be7-4d39-b383-87490e9d7adc")]
            public virtual RanorexDemoRepositoryFolders.BookAFlightFolder BookAFlight
            {
                get { return _bookaflight; }
            }

            /// <summary>
            /// The FlightConfirmation folder.
            /// </summary>
            [RepositoryFolder("4f4cd40e-ec23-4ef8-b2a8-a7c9d7eead36")]
            public virtual RanorexDemoRepositoryFolders.FlightConfirmationFolder FlightConfirmation
            {
                get { return _flightconfirmation; }
            }
        }

        /// <summary>
        /// The BookAFlightFolder folder.
        /// </summary>
        [RepositoryFolder("08c177fb-6be7-4d39-b383-87490e9d7adc")]
        public partial class BookAFlightFolder : RepoGenBaseFolder
        {
            RepoItemInfo _triptypeInfo;
            RepoItemInfo _passcountInfo;
            RepoItemInfo _toportInfo;
            RepoItemInfo _businessclassInfo;

            /// <summary>
            /// Creates a new BookAFlight  folder.
            /// </summary>
            public BookAFlightFolder(RepoGenBaseFolder parentFolder) :
                    base("BookAFlight", ".//table/?/?/tr/td[2]/table/tbody/tr[4]/?/?/table/?/?/tr/td[2]/table/tbody/tr[5]/?/?/form[@name='findflight']/table", parentFolder, 30000, null, false, "08c177fb-6be7-4d39-b383-87490e9d7adc", "")
            {
                _triptypeInfo = new RepoItemInfo(this, "TripType", "tbody/tr[2]/td[2]/?/?/font[@innertext~'^\\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ ']/input[@type='radio' and @value='oneway']", 30000, null, "c40a6713-d48d-447a-8768-cfff61538245");
                _passcountInfo = new RepoItemInfo(this, "PassCount", "tbody/tr[3]/td[2]/?/?/select[@name='passCount']", 30000, null, "f047aa0b-67b4-4ce7-b82a-4b5a0038a47f");
                _toportInfo = new RepoItemInfo(this, "ToPort", "tbody/tr[6]/td[2]/select[@name='toPort']", 30000, null, "faf823f6-65cf-42a9-a64d-0627a74810cc");
                _businessclassInfo = new RepoItemInfo(this, "BusinessClass", "tbody/tr[9]/td[2]/?/?/font[@innertext~'^Economy\\ class\\ \\ \\ \\ \\ \\ \\ \\ \\ \\ ']/input[@type='radio' and @value='Business']", 30000, null, "bd727743-0bef-468b-b8ae-f11d67e35e97");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("08c177fb-6be7-4d39-b383-87490e9d7adc")]
            public virtual Ranorex.Table Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("08c177fb-6be7-4d39-b383-87490e9d7adc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TripType item.
            /// </summary>
            [RepositoryItem("c40a6713-d48d-447a-8768-cfff61538245")]
            public virtual Ranorex.InputTag TripType
            {
                get
                {
                    return _triptypeInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The TripType item info.
            /// </summary>
            [RepositoryItemInfo("c40a6713-d48d-447a-8768-cfff61538245")]
            public virtual RepoItemInfo TripTypeInfo
            {
                get
                {
                    return _triptypeInfo;
                }
            }

            /// <summary>
            /// The PassCount item.
            /// </summary>
            [RepositoryItem("f047aa0b-67b4-4ce7-b82a-4b5a0038a47f")]
            public virtual Ranorex.SelectTag PassCount
            {
                get
                {
                    return _passcountInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The PassCount item info.
            /// </summary>
            [RepositoryItemInfo("f047aa0b-67b4-4ce7-b82a-4b5a0038a47f")]
            public virtual RepoItemInfo PassCountInfo
            {
                get
                {
                    return _passcountInfo;
                }
            }

            /// <summary>
            /// The ToPort item.
            /// </summary>
            [RepositoryItem("faf823f6-65cf-42a9-a64d-0627a74810cc")]
            public virtual Ranorex.SelectTag ToPort
            {
                get
                {
                    return _toportInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The ToPort item info.
            /// </summary>
            [RepositoryItemInfo("faf823f6-65cf-42a9-a64d-0627a74810cc")]
            public virtual RepoItemInfo ToPortInfo
            {
                get
                {
                    return _toportInfo;
                }
            }

            /// <summary>
            /// The BusinessClass item.
            /// </summary>
            [RepositoryItem("bd727743-0bef-468b-b8ae-f11d67e35e97")]
            public virtual Ranorex.InputTag BusinessClass
            {
                get
                {
                    return _businessclassInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The BusinessClass item info.
            /// </summary>
            [RepositoryItemInfo("bd727743-0bef-468b-b8ae-f11d67e35e97")]
            public virtual RepoItemInfo BusinessClassInfo
            {
                get
                {
                    return _businessclassInfo;
                }
            }
        }

        /// <summary>
        /// The FlightConfirmationFolder folder.
        /// </summary>
        [RepositoryFolder("4f4cd40e-ec23-4ef8-b2a8-a7c9d7eead36")]
        public partial class FlightConfirmationFolder : RepoGenBaseFolder
        {
            RepoItemInfo _signoffInfo;
            RepoItemInfo _securepurachseInfo;
            RepoItemInfo _passfirst0Info;
            RepoItemInfo _passlast0Info;
            RepoItemInfo _passfirst1Info;
            RepoItemInfo _passlast1Info;
            RepoItemInfo _creditnumberInfo;
            RepoItemInfo _findflightsInfo;
            RepoItemInfo _reserveflightsInfo;
            RepoItemInfo _textfield_signonInfo;
            RepoItemInfo _btn_logoutInfo;
            RepoItemInfo _textfield_flightfinderInfo;
            RepoItemInfo _text_confirmationInfo;
            RepoItemInfo _creditcardInfo;
            RepoItemInfo _ccfrstnameInfo;
            RepoItemInfo _ccmidnameInfo;
            RepoItemInfo _cclastnameInfo;
            RepoItemInfo _text_flightnoInfo;
            RepoItemInfo _totalpriceincludinInfo;
            RepoItemInfo _signonInfo;

            /// <summary>
            /// Creates a new FlightConfirmation  folder.
            /// </summary>
            public FlightConfirmationFolder(RepoGenBaseFolder parentFolder) :
                    base("FlightConfirmation", "body/?/?/table/?/?/tr/td[2]/table", parentFolder, 30000, null, false, "4f4cd40e-ec23-4ef8-b2a8-a7c9d7eead36", "")
            {
                _signoffInfo = new RepoItemInfo(this, "SIGNOFF", "tbody/tr[2]/?/?/table/?/?/tr/td[1]/a[@innertext='SIGN-OFF']", 30000, null, "3f37da2f-a496-4980-b160-faef5eb76496");
                _securepurachseInfo = new RepoItemInfo(this, "SecurePurachse", "tbody/tr[4]/?/?/table/?/?/tr/td[2]/table/tbody/tr[5]/?/?/form[@name='bookflight']/table/tbody/tr[24]/?/?/input[@name='buyFlights']", 30000, null, "350e1ef1-6d0a-4a6e-a068-8e8608de991c");
                _passfirst0Info = new RepoItemInfo(this, "PassFirst0", "tbody/tr[4]/?/?/table/?/?/tr/td[2]/table/tbody/tr[5]/?/?/form[@name='bookflight']/table/tbody/tr[4]/?/?/table/tbody/tr[2]/td[1]/input[@name='passFirst0']", 30000, null, "5ff90230-e739-4257-9f3a-e41c1aec67a0");
                _passlast0Info = new RepoItemInfo(this, "PassLast0", "tbody/tr[4]/?/?/table/?/?/tr/td[2]/table/tbody/tr[5]/?/?/form[@name='bookflight']/table/tbody/tr[4]/?/?/table/tbody/tr[2]/td[2]/input[@name='passLast0']", 30000, null, "2c89ad0d-a494-475f-a6ea-a7a3a18d311a");
                _passfirst1Info = new RepoItemInfo(this, "PassFirst1", "tbody/tr[4]/?/?/table/?/?/tr/td[2]/table/tbody/tr[5]/?/?/form[@name='bookflight']/table/tbody/tr[5]/?/?/table/tbody/tr[2]/td[1]/input[@name='passFirst1']", 30000, null, "96ab21a8-b1be-4e10-9020-64716750b466");
                _passlast1Info = new RepoItemInfo(this, "PassLast1", "tbody/tr[4]/?/?/table/?/?/tr/td[2]/table/tbody/tr[5]/?/?/form[@name='bookflight']/table/tbody/tr[5]/?/?/table/tbody/tr[2]/td[2]/input[@name='passLast1']", 30000, null, "2f1407c3-6739-4462-a599-8201bf609e1d");
                _creditnumberInfo = new RepoItemInfo(this, "Creditnumber", "tbody/tr[4]/?/?/table/?/?/tr/td[2]/table/tbody/tr[5]/?/?/form[@name='bookflight']/table/tbody/tr[7]/?/?/table/tbody/tr[2]/td[2]/input[@name='creditnumber']", 30000, null, "d79a97cf-413e-4e29-909e-d7d14ab11175");
                _findflightsInfo = new RepoItemInfo(this, "FindFlights", "tbody/tr[4]/?/?/table/?/?/tr/td[2]/table/tbody/tr[5]/?/?/form[@name='findflight']/table/tbody/tr[14]/?/?/input[@name='findFlights']", 30000, null, "3b06d6e6-04af-4ec5-a053-006e05f2146e");
                _reserveflightsInfo = new RepoItemInfo(this, "ReserveFlights", "tbody/tr[4]/?/?/table/?/?/tr/td[2]/table/tbody/tr[5]/?/?/form[@name='results']/p/input[@name='reserveFlights']", 30000, null, "22d36be1-0e27-4797-856e-fb9217c545b1");
                _textfield_signonInfo = new RepoItemInfo(this, "Textfield_SignOn", "tbody/tr[4]/?/?/table/?/?/tr/td[2]/table/tbody/tr[1]/?/?/img[@src='http://newtours.demoaut.com/images/masts/mast_signon.gif']", 30000, null, "7c33b927-26de-453b-8ca8-77cb168d1274");
                _btn_logoutInfo = new RepoItemInfo(this, "Btn_Logout", "tbody/tr[4]/?/?/table/tbody/tr[1]/td[2]/table/tbody/tr[7]/?/?/table/?/?/tr/td[3]/a[@href~'^http://newtours\\.demoaut\\.c']/img[@src='http://newtours.demoaut.com/images/forms/Logout.gif']", 30000, null, "703940d9-b8f6-4300-a82b-02b557e5aa3b");
                _textfield_flightfinderInfo = new RepoItemInfo(this, "Textfield_FlightFinder", "tbody/tr[4]/?/?/table/?/?/tr/td[2]/table/tbody/tr[1]/?/?/img[@src='http://newtours.demoaut.com/images/masts/mast_flightfinder.gif']", 30000, null, "6978e879-6892-4d81-8ab8-bfc3c4eac43b");
                _text_confirmationInfo = new RepoItemInfo(this, "Text_Confirmation", "tbody/tr[4]/?/?/table/tbody/tr[1]/td[2]/table/tbody/tr[5]/?/?/table/tbody/tr[1]/?/?/table/?/?/tr/td[1]//font[@innertext~'^ Flight\\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ ']", 30000, null, "ff06e066-6071-4a92-bab9-3fef007eafb2");
                _creditcardInfo = new RepoItemInfo(this, "CreditCard", "tbody/tr[4]/?/?/table/?/?/tr/td[2]/table/tbody/tr[5]/?/?/form[@name='bookflight']/table/tbody/tr[7]/?/?/table/tbody/tr[2]/td[1]/select[@name='creditCard']", 30000, null, "f8efbe46-9d97-45d5-85c1-821d8b9a5a64");
                _ccfrstnameInfo = new RepoItemInfo(this, "CcFrstName", "tbody/tr[4]/?/?/table/?/?/tr/td[2]/table/tbody/tr[5]/?/?/form[@name='bookflight']/table/tbody/tr[8]/?/?/table/tbody/tr[2]/td[1]/input[@name='cc_frst_name']", 30000, null, "7db8777f-0df5-4195-a73f-b2d9596cb7fe");
                _ccmidnameInfo = new RepoItemInfo(this, "CcMidName", "tbody/tr[4]/?/?/table/?/?/tr/td[2]/table/tbody/tr[5]/?/?/form[@name='bookflight']/table/tbody/tr[8]/?/?/table/tbody/tr[2]/td[2]/input[@name='cc_mid_name']", 30000, null, "6aba7d08-4293-4757-ae5a-a7489c062b16");
                _cclastnameInfo = new RepoItemInfo(this, "CcLastName", "tbody/tr[4]/?/?/table/?/?/tr/td[2]/table/tbody/tr[5]/?/?/form[@name='bookflight']/table/tbody/tr[8]/?/?/table/tbody/tr[2]/td[3]/input[@name='cc_last_name']", 30000, null, "b2df0653-1098-4ea9-b445-d198b8c5516a");
                _text_flightnoInfo = new RepoItemInfo(this, "Text_FlightNo", "tbody/tr[4]/?/?/table/tbody/tr[1]/td[2]/table/tbody/tr[5]/?/?/table/tbody/tr[1]/?/?/table/?/?/tr/td[1]//font[@innertext~'^ Flight\\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ ']", 30000, null, "6aeafda3-bf8e-4ceb-869b-1751cc05cfdc");
                _totalpriceincludinInfo = new RepoItemInfo(this, "TotalPriceIncludin", "tbody/tr[4]/?/?/table/tbody/tr[1]/td[2]/table/tbody/tr[5]/?/?/table/tbody/tr[12]/?/?/table/tbody/tr[2]/td[1]//font[@innertext~'^Total\\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ \\ ']", 30000, null, "506c6e40-f57e-47b2-8ba5-4eb8cabaa4de");
                _signonInfo = new RepoItemInfo(this, "SIGNON", "tbody/tr[2]/?/?/table/?/?/tr/td[1]/a[@innertext='SIGN-ON']", 30000, null, "daee7fef-fff6-4e60-9230-f37eb0b436f2");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4f4cd40e-ec23-4ef8-b2a8-a7c9d7eead36")]
            public virtual Ranorex.Table Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Table>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4f4cd40e-ec23-4ef8-b2a8-a7c9d7eead36")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SIGNOFF item.
            /// </summary>
            [RepositoryItem("3f37da2f-a496-4980-b160-faef5eb76496")]
            public virtual Ranorex.ATag SIGNOFF
            {
                get
                {
                    return _signoffInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The SIGNOFF item info.
            /// </summary>
            [RepositoryItemInfo("3f37da2f-a496-4980-b160-faef5eb76496")]
            public virtual RepoItemInfo SIGNOFFInfo
            {
                get
                {
                    return _signoffInfo;
                }
            }

            /// <summary>
            /// The SecurePurachse item.
            /// </summary>
            [RepositoryItem("350e1ef1-6d0a-4a6e-a068-8e8608de991c")]
            public virtual Ranorex.InputTag SecurePurachse
            {
                get
                {
                    return _securepurachseInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The SecurePurachse item info.
            /// </summary>
            [RepositoryItemInfo("350e1ef1-6d0a-4a6e-a068-8e8608de991c")]
            public virtual RepoItemInfo SecurePurachseInfo
            {
                get
                {
                    return _securepurachseInfo;
                }
            }

            /// <summary>
            /// The PassFirst0 item.
            /// </summary>
            [RepositoryItem("5ff90230-e739-4257-9f3a-e41c1aec67a0")]
            public virtual Ranorex.InputTag PassFirst0
            {
                get
                {
                    return _passfirst0Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The PassFirst0 item info.
            /// </summary>
            [RepositoryItemInfo("5ff90230-e739-4257-9f3a-e41c1aec67a0")]
            public virtual RepoItemInfo PassFirst0Info
            {
                get
                {
                    return _passfirst0Info;
                }
            }

            /// <summary>
            /// The PassLast0 item.
            /// </summary>
            [RepositoryItem("2c89ad0d-a494-475f-a6ea-a7a3a18d311a")]
            public virtual Ranorex.InputTag PassLast0
            {
                get
                {
                    return _passlast0Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The PassLast0 item info.
            /// </summary>
            [RepositoryItemInfo("2c89ad0d-a494-475f-a6ea-a7a3a18d311a")]
            public virtual RepoItemInfo PassLast0Info
            {
                get
                {
                    return _passlast0Info;
                }
            }

            /// <summary>
            /// The PassFirst1 item.
            /// </summary>
            [RepositoryItem("96ab21a8-b1be-4e10-9020-64716750b466")]
            public virtual Ranorex.InputTag PassFirst1
            {
                get
                {
                    return _passfirst1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The PassFirst1 item info.
            /// </summary>
            [RepositoryItemInfo("96ab21a8-b1be-4e10-9020-64716750b466")]
            public virtual RepoItemInfo PassFirst1Info
            {
                get
                {
                    return _passfirst1Info;
                }
            }

            /// <summary>
            /// The PassLast1 item.
            /// </summary>
            [RepositoryItem("2f1407c3-6739-4462-a599-8201bf609e1d")]
            public virtual Ranorex.InputTag PassLast1
            {
                get
                {
                    return _passlast1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The PassLast1 item info.
            /// </summary>
            [RepositoryItemInfo("2f1407c3-6739-4462-a599-8201bf609e1d")]
            public virtual RepoItemInfo PassLast1Info
            {
                get
                {
                    return _passlast1Info;
                }
            }

            /// <summary>
            /// The Creditnumber item.
            /// </summary>
            [RepositoryItem("d79a97cf-413e-4e29-909e-d7d14ab11175")]
            public virtual Ranorex.InputTag Creditnumber
            {
                get
                {
                    return _creditnumberInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Creditnumber item info.
            /// </summary>
            [RepositoryItemInfo("d79a97cf-413e-4e29-909e-d7d14ab11175")]
            public virtual RepoItemInfo CreditnumberInfo
            {
                get
                {
                    return _creditnumberInfo;
                }
            }

            /// <summary>
            /// The FindFlights item.
            /// </summary>
            [RepositoryItem("3b06d6e6-04af-4ec5-a053-006e05f2146e")]
            public virtual Ranorex.InputTag FindFlights
            {
                get
                {
                    return _findflightsInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The FindFlights item info.
            /// </summary>
            [RepositoryItemInfo("3b06d6e6-04af-4ec5-a053-006e05f2146e")]
            public virtual RepoItemInfo FindFlightsInfo
            {
                get
                {
                    return _findflightsInfo;
                }
            }

            /// <summary>
            /// The ReserveFlights item.
            /// </summary>
            [RepositoryItem("22d36be1-0e27-4797-856e-fb9217c545b1")]
            public virtual Ranorex.InputTag ReserveFlights
            {
                get
                {
                    return _reserveflightsInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The ReserveFlights item info.
            /// </summary>
            [RepositoryItemInfo("22d36be1-0e27-4797-856e-fb9217c545b1")]
            public virtual RepoItemInfo ReserveFlightsInfo
            {
                get
                {
                    return _reserveflightsInfo;
                }
            }

            /// <summary>
            /// The Textfield_SignOn item.
            /// </summary>
            [RepositoryItem("7c33b927-26de-453b-8ca8-77cb168d1274")]
            public virtual Ranorex.ImgTag Textfield_SignOn
            {
                get
                {
                    return _textfield_signonInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The Textfield_SignOn item info.
            /// </summary>
            [RepositoryItemInfo("7c33b927-26de-453b-8ca8-77cb168d1274")]
            public virtual RepoItemInfo Textfield_SignOnInfo
            {
                get
                {
                    return _textfield_signonInfo;
                }
            }

            /// <summary>
            /// The Btn_Logout item.
            /// </summary>
            [RepositoryItem("703940d9-b8f6-4300-a82b-02b557e5aa3b")]
            public virtual Ranorex.ImgTag Btn_Logout
            {
                get
                {
                    return _btn_logoutInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The Btn_Logout item info.
            /// </summary>
            [RepositoryItemInfo("703940d9-b8f6-4300-a82b-02b557e5aa3b")]
            public virtual RepoItemInfo Btn_LogoutInfo
            {
                get
                {
                    return _btn_logoutInfo;
                }
            }

            /// <summary>
            /// The Textfield_FlightFinder item.
            /// </summary>
            [RepositoryItem("6978e879-6892-4d81-8ab8-bfc3c4eac43b")]
            public virtual Ranorex.ImgTag Textfield_FlightFinder
            {
                get
                {
                    return _textfield_flightfinderInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The Textfield_FlightFinder item info.
            /// </summary>
            [RepositoryItemInfo("6978e879-6892-4d81-8ab8-bfc3c4eac43b")]
            public virtual RepoItemInfo Textfield_FlightFinderInfo
            {
                get
                {
                    return _textfield_flightfinderInfo;
                }
            }

            /// <summary>
            /// The Text_Confirmation item.
            /// </summary>
            [RepositoryItem("ff06e066-6071-4a92-bab9-3fef007eafb2")]
            public virtual Ranorex.FontTag Text_Confirmation
            {
                get
                {
                    return _text_confirmationInfo.CreateAdapter<Ranorex.FontTag>(true);
                }
            }

            /// <summary>
            /// The Text_Confirmation item info.
            /// </summary>
            [RepositoryItemInfo("ff06e066-6071-4a92-bab9-3fef007eafb2")]
            public virtual RepoItemInfo Text_ConfirmationInfo
            {
                get
                {
                    return _text_confirmationInfo;
                }
            }

            /// <summary>
            /// The CreditCard item.
            /// </summary>
            [RepositoryItem("f8efbe46-9d97-45d5-85c1-821d8b9a5a64")]
            public virtual Ranorex.SelectTag CreditCard
            {
                get
                {
                    return _creditcardInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The CreditCard item info.
            /// </summary>
            [RepositoryItemInfo("f8efbe46-9d97-45d5-85c1-821d8b9a5a64")]
            public virtual RepoItemInfo CreditCardInfo
            {
                get
                {
                    return _creditcardInfo;
                }
            }

            /// <summary>
            /// The CcFrstName item.
            /// </summary>
            [RepositoryItem("7db8777f-0df5-4195-a73f-b2d9596cb7fe")]
            public virtual Ranorex.InputTag CcFrstName
            {
                get
                {
                    return _ccfrstnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The CcFrstName item info.
            /// </summary>
            [RepositoryItemInfo("7db8777f-0df5-4195-a73f-b2d9596cb7fe")]
            public virtual RepoItemInfo CcFrstNameInfo
            {
                get
                {
                    return _ccfrstnameInfo;
                }
            }

            /// <summary>
            /// The CcMidName item.
            /// </summary>
            [RepositoryItem("6aba7d08-4293-4757-ae5a-a7489c062b16")]
            public virtual Ranorex.InputTag CcMidName
            {
                get
                {
                    return _ccmidnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The CcMidName item info.
            /// </summary>
            [RepositoryItemInfo("6aba7d08-4293-4757-ae5a-a7489c062b16")]
            public virtual RepoItemInfo CcMidNameInfo
            {
                get
                {
                    return _ccmidnameInfo;
                }
            }

            /// <summary>
            /// The CcLastName item.
            /// </summary>
            [RepositoryItem("b2df0653-1098-4ea9-b445-d198b8c5516a")]
            public virtual Ranorex.InputTag CcLastName
            {
                get
                {
                    return _cclastnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The CcLastName item info.
            /// </summary>
            [RepositoryItemInfo("b2df0653-1098-4ea9-b445-d198b8c5516a")]
            public virtual RepoItemInfo CcLastNameInfo
            {
                get
                {
                    return _cclastnameInfo;
                }
            }

            /// <summary>
            /// The Text_FlightNo item.
            /// </summary>
            [RepositoryItem("6aeafda3-bf8e-4ceb-869b-1751cc05cfdc")]
            public virtual Ranorex.FontTag Text_FlightNo
            {
                get
                {
                    return _text_flightnoInfo.CreateAdapter<Ranorex.FontTag>(true);
                }
            }

            /// <summary>
            /// The Text_FlightNo item info.
            /// </summary>
            [RepositoryItemInfo("6aeafda3-bf8e-4ceb-869b-1751cc05cfdc")]
            public virtual RepoItemInfo Text_FlightNoInfo
            {
                get
                {
                    return _text_flightnoInfo;
                }
            }

            /// <summary>
            /// The TotalPriceIncludin item.
            /// </summary>
            [RepositoryItem("506c6e40-f57e-47b2-8ba5-4eb8cabaa4de")]
            public virtual Ranorex.FontTag TotalPriceIncludin
            {
                get
                {
                    return _totalpriceincludinInfo.CreateAdapter<Ranorex.FontTag>(true);
                }
            }

            /// <summary>
            /// The TotalPriceIncludin item info.
            /// </summary>
            [RepositoryItemInfo("506c6e40-f57e-47b2-8ba5-4eb8cabaa4de")]
            public virtual RepoItemInfo TotalPriceIncludinInfo
            {
                get
                {
                    return _totalpriceincludinInfo;
                }
            }

            /// <summary>
            /// The SIGNON item.
            /// </summary>
            [RepositoryItem("daee7fef-fff6-4e60-9230-f37eb0b436f2")]
            public virtual Ranorex.ATag SIGNON
            {
                get
                {
                    return _signonInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The SIGNON item info.
            /// </summary>
            [RepositoryItemInfo("daee7fef-fff6-4e60-9230-f37eb0b436f2")]
            public virtual RepoItemInfo SIGNONInfo
            {
                get
                {
                    return _signonInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}