///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RanorexDemo.TestScript
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Login recording.
    /// </summary>
    [TestModule("474261a1-5482-42d1-b76c-d1323bd69748", ModuleType.Recording, 1)]
    public partial class Login : ITestModule
    {
        /// <summary>
        /// Holds an instance of the RanorexDemo.RanorexDemoRepository repository.
        /// </summary>
        public static RanorexDemo.RanorexDemoRepository repo = RanorexDemo.RanorexDemoRepository.Instance;

        static Login instance = new Login();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Login()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Login Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "7.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'http://demoaut.com/' with browser 'IE' in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("http://demoaut.com/", "IE", "", false, false, false, false, false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'mercury' with focus on 'Mercury.Home.UserName'.", repo.Mercury.Home.UserNameInfo, new RecordItemIndex(1));
            repo.Mercury.Home.UserName.PressKeys("mercury");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'mercury' with focus on 'Mercury.Home.Password'.", repo.Mercury.Home.PasswordInfo, new RecordItemIndex(2));
            repo.Mercury.Home.Password.PressKeys("mercury");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Mercury.Home.Login' at Center.", repo.Mercury.Home.LoginInfo, new RecordItemIndex(3));
            repo.Mercury.Home.Login.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 10s for item 'MercuryFlight.FlightConfirmation.Textfield_FlightFinder' to exist.", repo.MercuryFlight.FlightConfirmation.Textfield_FlightFinderInfo, new ActionTimeout(10000), new RecordItemIndex(4));
            repo.MercuryFlight.FlightConfirmation.Textfield_FlightFinderInfo.WaitForExists(10000);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
